## Import Data

In [73]:
import pandas as pd

In [74]:
bw = pd.DataFrame(pd.read_csv("bw.csv"))
bw

      SPREFID      USUBJID  BWORRES BWORRESU  BWDY SEX trial_set_description
0      HCD-03  HCD-03-0088    183.0        g    20   F                    CG
1      HCD-03  HCD-03-0088    149.0        g     5   F                    CG
2      HCD-03  HCD-03-0088    192.0        g    29   F                    CG
3      HCD-03  HCD-03-0088    155.0        g     9   F                    CG
4      HCD-03  HCD-03-0088    159.0        g    13   F                    CG
...       ...          ...      ...      ...   ...  ..                   ...
10340  HCD-11  HCD-11-0005    216.0        g     3   M                    CG
10341  HCD-11  HCD-11-0005    274.0        g    23   M                    CG
10342  HCD-11  HCD-11-0005    275.0        g    24   M                    CG
10343  HCD-11  HCD-11-0005    220.0        g     4   M                    CG
10344  HCD-11  HCD-11-0005    276.0        g    25   M                    CG

[10345 rows x 7 columns]

In [75]:
bw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10345 entries, 0 to 10344
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                10345 non-null  object
 1   USUBJID                10345 non-null  object
 2   BWORRES                10345 non-null  float64
 3   BWORRESU               10345 non-null  object
 4   BWDY                   10345 non-null  int64
 5   SEX                    10345 non-null  object
 6   trial_set_description  10345 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 565.9+ KB

In [76]:
cl = pd.DataFrame(pd.read_csv("cl.csv"))
cl

,SPREFID,USUBJID,CLLOC,STUDY_WEEK,CLORRES,CLRESCAT,CLSTAT,CLREASND,CLCAT,CLSEV,CLRFTDTC,CLTPTNUM,CLDY,SEX,trial_set_description
0,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-04-30T07:04:00Z,1.0,15,F,CG
1,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-04-30T09:32:00Z,2.0,15,F,CG
2,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-05-01T08:36:00Z,1.0,16,F,CG
3,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-05-01T10:39:00Z,2.0,16,F,CG
4,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-05-02T09:32:00Z,1.0,17,F,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31606,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Pupil Reflex,NaN,2018-04-26T09:01:09Z,1.0,-4,F,CG
31607,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Open-Field Observation,NaN,2018-05-09T07:16:18Z,1.0,10,F,CG
31608,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2018-05-17T07:16:56Z,2.0,18,F,CG
31609,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2018-05-15T09:59:47Z,3.0,16,F,CG
31610,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2018-05-12T08:57:36Z,2.0,13,F,CG

In [77]:
cl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31611 entries, 0 to 31610
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                31611 non-null  object
 1   USUBJID                31611 non-null  object
 2   CLLOC                  297 non-null    object
 3   STUDY_WEEK             19928 non-null  float64
 4   CLORRES                31611 non-null  object
 5   CLRESCAT               31611 non-null  object
 6   CLSTAT                 19928 non-null  object
 7   CLREASND               0 non-null      float64
 8   CLCAT                  31611 non-null  object
 9   CLSEV                  108 non-null    object
 10  CLRFTDTC               31611 non-null  object
 11  CLTPTNUM               30718 non-null  float64
 12  CLDY                   31611 non-null  int64
 13  SEX                    31611 non-null  object
 14  trial_set_description  31611 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 3.6+ MB

In [78]:
fw = pd.DataFrame(pd.read_csv("fw.csv"))
fw

,SPREFID,USUBJID,SEX,FWTESTCD,FWTEST,FWORRES,FWORRESU,FWDY,FWENDY,FWSTAT,FWREASND,trial_set_description
0,HCD-14,HCD-14-0002,M,WC,Water Consumption,28.0,g/day,1,8,Y,NaN,CG
1,HCD-14,HCD-14-0001,M,WC,Water Consumption,28.0,g/day,1,8,Y,NaN,CG
2,HCD-14,HCD-14-0002,M,WC,Water Consumption,30.0,g/day,8,15,Y,NaN,CG
3,HCD-14,HCD-14-0001,M,WC,Water Consumption,30.0,g/day,8,15,Y,NaN,CG
4,HCD-14,HCD-14-0002,M,WC,Water Consumption,28.0,g/day,15,22,Y,NaN,CG
...,...,...,...,...,...,...,...,...,...,...,...,...
2387,HCD-02,HCD-02-0103,F,FC,Food Consumption,18.0,g/day,8,15,Y,NaN,CG
2388,HCD-02,HCD-02-0102,F,FC,Food Consumption,17.0,g/day,15,22,Y,NaN,CG
2389,HCD-02,HCD-02-0103,F,FC,Food Consumption,17.0,g/day,15,22,Y,NaN,CG
2390,HCD-02,HCD-02-0102,F,FC,Food Consumption,15.0,g/day,22,29,Y,NaN,CG
2391,HCD-02,HCD-02-0103,F,FC,Food Consumption,15.0,g/day,22,29,Y,NaN,CG

In [79]:
fw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                2392 non-null   object
 1   USUBJID                2392 non-null   object
 2   SEX                    2392 non-null   object
 3   FWTESTCD               2392 non-null   object
 4   FWTEST                 2392 non-null   object
 5   FWORRES                2392 non-null   float64
 6   FWORRESU               2392 non-null   object
 7   FWDY                   2392 non-null   int64
 8   FWENDY                 2392 non-null   int64
 9   FWSTAT                 2392 non-null   object
 10  FWREASND               0 non-null      float64
 11  trial_set_description  2392 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 224.4+ KB

In [80]:
lb = pd.DataFrame(pd.read_csv("lb.csv"))
lb

,SPREFID,USUBJID,LBTEST,LBTESTCD,LBCAT,LBORRES,LBORRESU,LBMETHOD,LBSPEC,LBDY,trial_set_description,SEX
0,HCD-13,HCD-13-0042,Chloride,CL,CLINICAL CHEMISTRY,103.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
1,HCD-13,HCD-13-0044,Chloride,CL,CLINICAL CHEMISTRY,103.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
2,HCD-13,HCD-13-0049,Chloride,CL,CLINICAL CHEMISTRY,106.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
3,HCD-13,HCD-13-0047,Chloride,CL,CLINICAL CHEMISTRY,102.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
4,HCD-13,HCD-13-0048,Chloride,CL,CLINICAL CHEMISTRY,105.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
...,...,...,...,...,...,...,...,...,...,...,...,...
15452,HCD-02,HCD-02-0006,Volume,VOLUME,URINALYSIS,10.0,ml,iBroker:Volume,URINE,24,CG,M
15453,HCD-02,HCD-02-0008,Volume,VOLUME,URINALYSIS,9.7,ml,iBroker:Volume,URINE,24,CG,M
15454,HCD-02,HCD-02-0001,Volume,VOLUME,URINALYSIS,6.3,ml,iBroker:Volume,URINE,24,CG,M
15455,HCD-02,HCD-02-0009,Volume,VOLUME,URINALYSIS,3.8,ml,iBroker:Volume,URINE,24,CG,M
15456,HCD-02,HCD-02-0010,Volume,VOLUME,URINALYSIS,5.0,ml,iBroker:Volume,URINE,24,CG,M

In [81]:
lb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15457 entries, 0 to 15456
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                15457 non-null  object
 1   USUBJID                15457 non-null  object
 2   LBTEST                 15457 non-null  object
 3   LBTESTCD               15457 non-null  object
 4   LBCAT                  15457 non-null  object
 5   LBORRES                15457 non-null  float64
 6   LBORRESU               15457 non-null  object
 7   LBMETHOD               13838 non-null  object
 8   LBSPEC                 15457 non-null  object
 9   LBDY                   15457 non-null  int64
 10  trial_set_description  15457 non-null  object
 11  SEX                    15457 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 1.4+ MB

In [82]:
LB_mapping = pd.DataFrame(pd.read_excel("LB_mapping.xlsx"))
LB_mapping

,LBTEST_new,LBTEST_old,LBTESTCD
0,CALCIUM,CALCIUM,CA
1,CALCIUM,CALCIUM COBAS,CA
2,CALCIUM,CALCIUM URINE,CA
3,CALCIUM,URINE CALCIUM,CA
4,CALCIUM,CALCIUM IN SERUM,CA
...,...,...,...
300,PROTEIN/CREATININE,PROTEIN/CREATININE,PROCRC
301,PROTEIN/CREATININE,PROTEIN PER MMOL CREATININE URINE,PROCRC
302,PROTEIN/CREATININE,51URINE TOTAL PROTEIN/51URINE CREATININE MMOL/L,PROCRC
303,PROTEIN PER SAMPLING PERIOD UVOL,PROTEIN PER SAMPLING PERIOD UVOL,PROCRC
304,CREATININE PER URINE VOLUME,CREATININE PER SAMPLING PERIOD,CREUVOC

In [83]:
LB_unit_mapping = pd.DataFrame(pd.read_excel("LB_unit_mapping.xlsx"))
LB_unit_mapping

,LBTEST_old,LBTESTCD_old,LBSPEC_old,LBORRESU_old,meanval,LBTEST_new,LBTESTCD_new,LBSPEC_new,LBORRESU_new
0,7-ETHOXYCOUMARIN DEETHYLASE,ECOD,7-Ethoxycoumarin Deethylase,nmol/(g*min),3.271429,7-ETHOXYCOUMARIN DEETHYLASE,ECOD,Liver Bio Chemie,nmol/(g*min)
1,7-ETHOXYCOUMARIN DEETHYLASE,ECOD,LIVER,nmol/(g*min),2.866667,7-ETHOXYCOUMARIN DEETHYLASE,ECOD,Liver Bio Chemie,nmol/(g*min)
2,7-ETHOXYCOUMARIN DEETHYLASE,ECOD,Liver Bio Chemie,nmol/(g*min),3.264286,7-ETHOXYCOUMARIN DEETHYLASE,ECOD,Liver Bio Chemie,nmol/(g*min)
3,7-ETHOXYRESORUFIN DEETHYLASE,EROD,7-Ethoxyresorufin Deethylase,nmol/(g*min),0.218286,7-ETHOXYRESORUFIN DEETHYLASE,EROD,Liver Bio Chemie,nmol/(g*min)
4,7-ETHOXYRESORUFIN DEETHYLASE,EROD,LIVER,nmol/(g*min),0.137778,7-ETHOXYRESORUFIN DEETHYLASE,EROD,Liver Bio Chemie,nmol/(g*min)
...,...,...,...,...,...,...,...,...,...
288,WEIGHT,WEIGHT_TESTIS,TESTES,g,3.225984,WEIGHT,WEIGHT_TESTIS,TESTIS,g
289,WEIGHT,WEIGHT_TESTIS,TESTIS,g,3.354471,WEIGHT,WEIGHT_TESTIS,TESTIS,g
290,WEIGHT,WEIGHT_THYMUS,THYMUS,g,0.446672,WEIGHT,WEIGHT_THYMUS,THYMUS,g
291,WEIGHT,WEIGHT_UTERUS,UTERUS,g,0.667727,WEIGHT,WEIGHT_UTERUS,UTERUS,g
292,YEAST CELLS,YEAST,URINE,NaN,0.000000,YEAST CELLS,YEAST,URINE,NaN

In [84]:
LB_unit_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LBTEST_old    293 non-null    object
 1   LBTESTCD_old  254 non-null    object
 2   LBSPEC_old    258 non-null    object
 3   LBORRESU_old  241 non-null    object
 4   meanval       250 non-null    float64
 5   LBTEST_new    293 non-null    object
 6   LBTESTCD_new  293 non-null    object
 7   LBSPEC_new    293 non-null    object
 8   LBORRESU_new  241 non-null    object
dtypes: float64(1), object(8)
memory usage: 20.7+ KB

In [85]:
LBTEST_dictionary = pd.DataFrame(pd.read_csv("LBTEST_dictionary.csv"))
LBTEST_dictionary

                       LBTEST  LBTESTCD       LBSPEC
0                     Glucose      GLUC        SERUM
1       Large Unstained Cells   LGUNSCE  WHOLE BLOOD
2    Alanine Aminotransferase       ALT        SERUM
3                   Basophils      BASO  WHOLE BLOOD
4                      Volume    VOLUME        URINE
..                        ...       ...          ...
497                   ImFun01   IMFUN01  WHOLE BLOOD
498                   ImFun28   IMFUN28  WHOLE BLOOD
499                   ImFun24   IMFUN24  WHOLE BLOOD
500    b conjugated bilirubin     BCBIL        SERUM
501                  NAG/CREA  U-NAG/CR        URINE

[502 rows x 3 columns]

In [86]:
LBTEST_dictionary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LBTEST    502 non-null    object
 1   LBTESTCD  502 non-null    object
 2   LBSPEC    502 non-null    object
dtypes: object(3)
memory usage: 11.9+ KB

In [87]:
legacy_LB = pd.DataFrame(pd.read_excel("legacy_LB.xlsx"))
legacy_LB

    LBTESTCD  LBSPEC LBORRESU                    LBTEST
0        ALB   SERUM      g/l                   ALBUMIN
1        ALP   SERUM      U/l      ALKALINE PHOSPHATASE
2        ALT   SERUM      U/l  ALANINE AMINOTRANSFERASE
3   AMORPHSD   URINE      NaN        AMORPHOUS SEDIMENT
4      ANISO  PLASMA      NaN                ANISOCYTES
..       ...     ...      ...                       ...
78   UROTHCE   URINE      NaN          UROTHELIAL CELLS
79    VOLUME   URINE       ml                    VOLUME
80       WBC   URINE      NaN                LEUKOCYTES
81       WBC  PLASMA      G/l                LEUKOCYTES
82     YEAST   URINE      NaN               YEAST CELLS

[83 rows x 4 columns]

In [88]:
legacy_LB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LBTESTCD  83 non-null     object
 1   LBSPEC    83 non-null     object
 2   LBORRESU  53 non-null     object
 3   LBTEST    83 non-null     object
dtypes: object(4)
memory usage: 2.7+ KB

In [89]:
ma = pd.DataFrame(pd.read_csv("ma.csv"))
ma

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
0,HCD-10,HCD-10-0082,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
1,HCD-10,HCD-10-0085,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
2,HCD-10,HCD-10-0081,OVIDUCT,NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
3,HCD-10,HCD-10-0081,"LARGE INTESTINE, CECUM",NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
4,HCD-10,HCD-10-0081,LIVER,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,HCD-09,HCD-09-0019,SPINAL CORD,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1902,HCD-09,HCD-09-0019,"GLAND, SALIVARY",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1903,HCD-09,HCD-09-0019,"GLAND, PARATHYROID",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1904,HCD-09,HCD-09-0074,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:48:40Z,Gross Pathological Examination,GROSPATH,1,F,CG
1905,HCD-09,HCD-09-0078,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:22:21Z,Gross Pathological Examination,GROSPATH,1,F,CG

In [90]:
ma.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1906 entries, 0 to 1905
Data columns (total 16 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SPREFID                                1906 non-null   object
 1   USUBJID                                1906 non-null   object
 2   MASPEC                                 1906 non-null   object
 3   MASEVN                                 0 non-null      float64
 4   MASEV                                  0 non-null      float64
 5   MAORRES                                1906 non-null   object
 6   MALAT                                  553 non-null    object
 7   MASTAT                                 0 non-null      float64
 8   MAREASND                               0 non-null      float64
 9   MADY                                   1906 non-null   int64
 10  MADTC                                  1906 non-null   object
 11  MATEST                                 1906 non-null   object
 12  MATESTCD                               1906 non-null   object
 13  finding_is_unremarkable_or_incomplete  1906 non-null   int64
 14  SEX                                    1906 non-null   object
 15  trial_set_description                  1906 non-null   object
dtypes: float64(4), int64(2), object(10)
memory usage: 238.4+ KB

In [91]:
mi = pd.DataFrame(pd.read_csv("mi.csv"))
mi

,SPREFID,USUBJID,SEX,MISPEC,MISEVTXT,MISEV,MIORRES,MIRESCAT,MIDY,trial_set_description
0,HCD-05,HCD-05-0015,M,"SMALL INTESTINE, ILEUM",NaN,NaN,UNREMARKABLE,NaN,58,CG
1,HCD-05,HCD-05-0015,M,"LARGE INTESTINE, RECTUM",NaN,NaN,UNREMARKABLE,NaN,58,CG
2,HCD-05,HCD-05-0015,M,TRACHEA,NaN,NaN,UNREMARKABLE,NaN,58,CG
3,HCD-05,HCD-05-0015,M,ESOPHAGUS,NaN,NaN,UNREMARKABLE,NaN,58,CG
4,HCD-05,HCD-05-0015,M,PEYER'S PATCH,NaN,NaN,UNREMARKABLE,NaN,58,CG
...,...,...,...,...,...,...,...,...,...,...
14126,HCD-07,HCD-07-0001,M,SKIN,NaN,NaN,UNREMARKABLE,NaN,29,CG
14127,HCD-07,HCD-07-0001,M,EYE,NaN,NaN,UNREMARKABLE,NaN,29,CG
14128,HCD-07,HCD-07-0001,M,"LARGE INTESTINE, RECTUM",NaN,NaN,UNREMARKABLE,NaN,29,CG
14129,HCD-07,HCD-07-0001,M,SPINAL CORD,NaN,NaN,UNREMARKABLE,NaN,29,CG
14130,HCD-07,HCD-07-0001,M,TESTIS,NaN,NaN,UNREMARKABLE,NaN,29,CG

In [92]:
mi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14131 entries, 0 to 14130
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                14131 non-null  object
 1   USUBJID                14131 non-null  object
 2   SEX                    14131 non-null  object
 3   MISPEC                 14131 non-null  object
 4   MISEVTXT               957 non-null    object
 5   MISEV                  957 non-null    float64
 6   MIORRES                11406 non-null  object
 7   MIRESCAT               1086 non-null   object
 8   MIDY                   14131 non-null  int64
 9   trial_set_description  14131 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.1+ MB

In [93]:
om = pd.DataFrame(pd.read_csv("om.csv"))
om

,SPREFID,USUBJID,OMEXCLFL,OMSTAT,OMREASND,OMTESTCD,OMTEST,OMSPEC,OMSTRES,OMSTRESU,OMDY,SEX,trial_set_description
0,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,THYMUS,0.18757,%,29,M,CG
1,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,THYMUS,0.52200,g,29,M,CG
2,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,SPLEEN,0.19799,%,29,M,CG
3,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,SPLEEN,0.55100,g,29,M,CG
4,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, ADRENAL",0.01365,%,29,M,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5889,HCD-12,HCD-12-0009,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,EPIDIDYMIS,0.36779,%,31,M,CG
5890,HCD-12,HCD-12-0009,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, PROSTATE",0.67400,g,31,M,CG
5891,HCD-12,HCD-12-0009,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, PROSTATE",0.21840,%,31,M,CG
5892,HCD-12,HCD-12-0009,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, COAGULATING",0.85600,g,31,M,CG
5893,HCD-12,HCD-12-0009,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, ADRENAL",0.01912,%,31,M,CG

In [94]:
om.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5894 entries, 0 to 5893
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                5894 non-null   object
 1   USUBJID                5894 non-null   object
 2   OMEXCLFL               0 non-null      float64
 3   OMSTAT                 0 non-null      float64
 4   OMREASND               0 non-null      float64
 5   OMTESTCD               5894 non-null   object
 6   OMTEST                 5894 non-null   object
 7   OMSPEC                 5894 non-null   object
 8   OMSTRES                5894 non-null   float64
 9   OMSTRESU               5894 non-null   object
 10  OMDY                   5894 non-null   int64
 11  SEX                    5894 non-null   object
 12  trial_set_description  5894 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 598.7+ KB

In [96]:
om_mapping = pd.DataFrame(pd.read_excel("om_mapping.xlsx"))
om_mapping

    OMTEST   OMTESTCD_new OMSPEC_new                             OMTESTCD_old
0     OWBW    OWBW_THYMUS     THYMUS                              OWBW_THYMUS
1   WEIGHT  WEIGHT_THYMUS     THYMUS                            WEIGHT_THYMUS
2   WEIGHT  WEIGHT_THYMUS     THYMUS                     WEIGHT_THYMUS WEIGHT
3     OWBW    OWBW_THYMUS     THYMUS  WEIGHT_THYMUS/TERMINAL BODYWEIGHT RATIO
4     OWBW    OWBW_SPLEEN     SPLEEN  WEIGHT_SPLEEN/TERMINAL BODYWEIGHT RATIO
..     ...            ...        ...                                      ...
77  WEIGHT  WEIGHT_UTERUS     UTERUS                     WEIGHT_UTERUS WEIGHT
78    OWBW     OWBW_OVARY      OVARY                             OWBW_OVARIES
79  WEIGHT   WEIGHT_OVARY      OVARY                           WEIGHT_OVARIES
80    OWBW     OWBW_OVARY      OVARY                               OWBW_OVARY
81  WEIGHT   WEIGHT_OVARY      OVARY                             WEIGHT_OVARY

[82 rows x 4 columns]

In [97]:
om_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OMTEST        82 non-null     object
 1   OMTESTCD_new  82 non-null     object
 2   OMSPEC_new    82 non-null     object
 3   OMTESTCD_old  82 non-null     object
dtypes: object(4)
memory usage: 2.7+ KB

In [98]:
ts = pd.DataFrame(pd.read_csv("ts.csv"))
ts

,SPREFID,SPECIES,STRAIN,AGE,AGEU,DOSDUR,ROUTE,TRTV,TSTFLOC,START_YEAR,STDSTDTC,STITLE
0,HCD-09,RAT,WISTAR HAN,7-8,WEEKS,4 week,INTRAGASTRIC,Ethanol/KolliphorHS15/WaterfI,"42096 Wuppertal, Germany",2018,2018-04-17,Repeated Dose Systemic Toxicity Study in Wista...
1,HCD-05,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-03-14,Repeated Dose Systemic Toxicity Study in Wista...
2,HCD-04,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-03-07,Repeated Dose Systemic Toxicity Study in Wista...
3,HCD-08,RAT,WISTAR HAN,NaN,WEEKS,4 week,ORAL,Kolliphor HS 15/ethanol/water (40/10/50; v/v/v),42096 Wuppertal,2018,2018-03-15,Repeated Dose Systemic Toxicity Study in Wista...
4,HCD-01,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,PEG 400 / Ethanol,"Wuppertal, Germany",2017,2017-01-10,4-Week Repeated Dose Systemic Toxicity Study i...
5,HCD-10,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2018,2018-06-05,Repeated Dose Systemic Toxicity Study in Wista...
6,HCD-12,RAT,WISTAR,NaN,WEEKS,4 week,ORAL,PEG 400/Ethanol (90/10; v/v),"GLP-Prufeinrichtung Early Development Bayer, 4...",2019,2019-04-08,4- Week Repeat Dose Systemic Toxicity Study in...
7,HCD-11,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2019,2019-03-26,Repeated Dose Systemic Toxicity Study in Male ...
8,HCD-06,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-03-21,4-Week Repeat Dose Systemic Toxicity Study in ...
9,HCD-07,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-06-02,4-Week Repeat Dose Systemic Toxicity Study in ...
10,HCD-14,RAT,WISTAR,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2020,2020-11-10,4-Week Repeat Dose Systemic Toxicity Study in ...
11,HCD-13,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,PEG400/Cremophor/Imwitor+SDS,"Wuppertal, Germany",2019,2019-10-29,Repeated Dose Systemic Toxicity Study in Rats ...
12,HCD-03,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-02-14,Repeated Dose Systemic Toxicity Study in Wista...
13,HCD-02,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-01-24,Repeated Dose Systemic Toxicity Study in Wista...

In [99]:
ts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SPREFID     14 non-null     object
 1   SPECIES     14 non-null     object
 2   STRAIN      14 non-null     object
 3   AGE         1 non-null      object
 4   AGEU        3 non-null      object
 5   DOSDUR      14 non-null     object
 6   ROUTE       14 non-null     object
 7   TRTV        14 non-null     object
 8   TSTFLOC     14 non-null     object
 9   START_YEAR  14 non-null     int64
 10  STDSTDTC    14 non-null     object
 11  STITLE      14 non-null     object
dtypes: int64(1), object(11)
memory usage: 1.4+ KB

In [100]:
LBTEST_dictionary = pd.DataFrame(pd.read_csv("LBTEST_dictionary.csv"))
LBTEST_dictionary

                       LBTEST  LBTESTCD       LBSPEC
0                     Glucose      GLUC        SERUM
1       Large Unstained Cells   LGUNSCE  WHOLE BLOOD
2    Alanine Aminotransferase       ALT        SERUM
3                   Basophils      BASO  WHOLE BLOOD
4                      Volume    VOLUME        URINE
..                        ...       ...          ...
497                   ImFun01   IMFUN01  WHOLE BLOOD
498                   ImFun28   IMFUN28  WHOLE BLOOD
499                   ImFun24   IMFUN24  WHOLE BLOOD
500    b conjugated bilirubin     BCBIL        SERUM
501                  NAG/CREA  U-NAG/CR        URINE

[502 rows x 3 columns]

In [101]:
LBTEST_dictionary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LBTEST    502 non-null    object
 1   LBTESTCD  502 non-null    object
 2   LBSPEC    502 non-null    object
dtypes: object(3)
memory usage: 11.9+ KB

## Data Analysis

In [102]:
bw

      SPREFID      USUBJID  BWORRES BWORRESU  BWDY SEX trial_set_description
0      HCD-03  HCD-03-0088    183.0        g    20   F                    CG
1      HCD-03  HCD-03-0088    149.0        g     5   F                    CG
2      HCD-03  HCD-03-0088    192.0        g    29   F                    CG
3      HCD-03  HCD-03-0088    155.0        g     9   F                    CG
4      HCD-03  HCD-03-0088    159.0        g    13   F                    CG
...       ...          ...      ...      ...   ...  ..                   ...
10340  HCD-11  HCD-11-0005    216.0        g     3   M                    CG
10341  HCD-11  HCD-11-0005    274.0        g    23   M                    CG
10342  HCD-11  HCD-11-0005    275.0        g    24   M                    CG
10343  HCD-11  HCD-11-0005    220.0        g     4   M                    CG
10344  HCD-11  HCD-11-0005    276.0        g    25   M                    CG

[10345 rows x 7 columns]

In [103]:
bw_Male = bw[bw["SEX"] == "M"]
bw_Male.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5222 entries, 35 to 10344
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                5222 non-null   object
 1   USUBJID                5222 non-null   object
 2   BWORRES                5222 non-null   float64
 3   BWORRESU               5222 non-null   object
 4   BWDY                   5222 non-null   int64
 5   SEX                    5222 non-null   object
 6   trial_set_description  5222 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 326.4+ KB

In [104]:
bw_Female = bw[bw["SEX"] == "F"]
bw_Female.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5123 entries, 0 to 10158
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                5123 non-null   object
 1   USUBJID                5123 non-null   object
 2   BWORRES                5123 non-null   float64
 3   BWORRESU               5123 non-null   object
 4   BWDY                   5123 non-null   int64
 5   SEX                    5123 non-null   object
 6   trial_set_description  5123 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 320.2+ KB

In [105]:
bw_trial_set_description = bw[bw["trial_set_description"] == "CG"]
bw_trial_set_description.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10345 entries, 0 to 10344
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                10345 non-null  object
 1   USUBJID                10345 non-null  object
 2   BWORRES                10345 non-null  float64
 3   BWORRESU               10345 non-null  object
 4   BWDY                   10345 non-null  int64
 5   SEX                    10345 non-null  object
 6   trial_set_description  10345 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 646.6+ KB

In [123]:
cl

,SPREFID,USUBJID,CLLOC,STUDY_WEEK,CLORRES,CLRESCAT,CLSTAT,CLREASND,CLCAT,CLSEV,CLRFTDTC,CLTPTNUM,CLDY,SEX,trial_set_description
0,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-04-30T07:04:00Z,1.0,15,F,CG
1,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-04-30T09:32:00Z,2.0,15,F,CG
2,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-05-01T08:36:00Z,1.0,16,F,CG
3,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-05-01T10:39:00Z,2.0,16,F,CG
4,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2019-05-02T09:32:00Z,1.0,17,F,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31606,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Pupil Reflex,NaN,2018-04-26T09:01:09Z,1.0,-4,F,CG
31607,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Open-Field Observation,NaN,2018-05-09T07:16:18Z,1.0,10,F,CG
31608,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2018-05-17T07:16:56Z,2.0,18,F,CG
31609,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2018-05-15T09:59:47Z,3.0,16,F,CG
31610,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,CLINICAL SIGNS,NaN,NaN,Detailed Clinical Observation,NaN,2018-05-12T08:57:36Z,2.0,13,F,CG

In [107]:
cl_male_OPHTHALMOLOGY = cl[(cl["CLRESCAT"] == "OPHTHALMOLOGY") & (cl["SEX"] == "M")]
cl_male_OPHTHALMOLOGY

,SPREFID,USUBJID,CLLOC,STUDY_WEEK,CLORRES,CLRESCAT,CLSTAT,CLREASND,CLCAT,CLSEV,CLRFTDTC,CLTPTNUM,CLDY,SEX,trial_set_description
150,HCD-12,HCD-12-0017,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology With Ophthalmoscope,NaN,2019-04-09T10:15:00Z,NaN,-7,M,CG
151,HCD-12,HCD-12-0017,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Pupil Reflex,NaN,2019-04-09T10:15:00Z,NaN,-7,M,CG
152,HCD-12,HCD-12-0017,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Slit-Lamp Observation,NaN,2019-04-09T10:16:00Z,NaN,-7,M,CG
188,HCD-14,HCD-14-0010,NaN,4.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY PUPIL REFLEX,NaN,2020-12-14T08:08:24Z,1.0,27,M,CG
194,HCD-14,HCD-14-0010,NaN,4.0,Iris:Pupillary filaments,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY SLIT-LAMP OBSERVATION,NaN,2020-12-14T08:18:34Z,1.0,27,M,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31362,HCD-04,HCD-04-0006,NaN,-1.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY PUPIL REFLEX,NaN,2017-03-10T08:10:44Z,3.0,-4,M,CG
31365,HCD-04,HCD-04-0006,NaN,-1.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY SLIT-LAMP OBSERVATION,NaN,2017-03-10T08:10:46Z,3.0,-4,M,CG
31367,HCD-04,HCD-04-0006,NaN,4.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY WITH OPHTHALMOSCOPE,NaN,2017-04-07T11:24:09Z,3.0,25,M,CG
31368,HCD-04,HCD-04-0006,NaN,4.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY PUPIL REFLEX,NaN,2017-04-07T11:24:08Z,3.0,25,M,CG
31369,HCD-04,HCD-04-0006,NaN,4.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY SLIT-LAMP OBSERVATION,NaN,2017-04-07T11:24:10Z,3.0,25,M,CG

In [108]:
cl_female_OPHTHALMOLOGY = cl[(cl["CLRESCAT"] == "OPHTHALMOLOGY") & (cl["SEX"] == "F")]
cl_female_OPHTHALMOLOGY

,SPREFID,USUBJID,CLLOC,STUDY_WEEK,CLORRES,CLRESCAT,CLSTAT,CLREASND,CLCAT,CLSEV,CLRFTDTC,CLTPTNUM,CLDY,SEX,trial_set_description
38,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology With Ophthalmoscope,NaN,2019-04-09T08:59:00Z,NaN,-7,F,CG
39,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Pupil Reflex,NaN,2019-04-09T08:58:00Z,NaN,-7,F,CG
40,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Slit-Lamp Observation,NaN,2019-04-09T08:59:00Z,NaN,-7,F,CG
67,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology With Ophthalmoscope,NaN,2019-05-10T11:04:00Z,4.0,25,F,CG
68,HCD-12,HCD-12-0083,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Pupil Reflex,NaN,2019-05-10T11:03:00Z,5.0,25,F,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31474,HCD-10,HCD-10-0077,NaN,-1.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY WITH OPHTHALMOSCOPE,NaN,2018-06-07T09:06:53Z,1.0,-5,F,CG
31477,HCD-10,HCD-10-0077,NaN,-1.0,NORMAL,OPHTHALMOLOGY,Y,NaN,OPHTHALMOLOGY PUPIL REFLEX,NaN,2018-06-07T09:06:52Z,1.0,-5,F,CG
31543,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology with Ophthalmoscope,NaN,2018-04-26T09:23:10Z,1.0,-4,F,CG
31544,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Slit-Lamp Observation,NaN,2018-04-26T09:23:12Z,1.0,-4,F,CG
31606,HCD-09,HCD-09-0092,NaN,NaN,NORMAL,OPHTHALMOLOGY,NaN,NaN,Ophthalmology Pupil Reflex,NaN,2018-04-26T09:01:09Z,1.0,-4,F,CG

In [109]:
cl_CLRESCAT_GROUP = cl["CLRESCAT"].unique()
cl_CLRESCAT_GROUP

array(['CLINICAL SIGNS', 'OPHTHALMOLOGY', 'PHYSICAL EXAM'], dtype=object)

In [110]:
cl_male_CLINICAL_SIGNS = cl[(cl["CLRESCAT"] == "CLINICAL SIGNS") & (cl["SEX"] == "M")]
cl_male_CLINICAL_SIGNS.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14644 entries, 75 to 31366
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                14644 non-null  object
 1   USUBJID                14644 non-null  object
 2   CLLOC                  83 non-null     object
 3   STUDY_WEEK             9230 non-null   float64
 4   CLORRES                14644 non-null  object
 5   CLRESCAT               14644 non-null  object
 6   CLSTAT                 9230 non-null   object
 7   CLREASND               0 non-null      float64
 8   CLCAT                  14644 non-null  object
 9   CLSEV                  0 non-null      object
 10  CLRFTDTC               14644 non-null  object
 11  CLTPTNUM               14296 non-null  float64
 12  CLDY                   14644 non-null  int64
 13  SEX                    14644 non-null  object
 14  trial_set_description  14644 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 1.8+ MB

In [111]:
cl_female_CLINICAL_SIGNS = cl[(cl["CLRESCAT"] == "CLINICAL SIGNS") & (cl["SEX"] == "F")]
cl_female_CLINICAL_SIGNS.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14595 entries, 0 to 31610
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                14595 non-null  object
 1   USUBJID                14595 non-null  object
 2   CLLOC                  204 non-null    object
 3   STUDY_WEEK             9089 non-null   float64
 4   CLORRES                14595 non-null  object
 5   CLRESCAT               14595 non-null  object
 6   CLSTAT                 9089 non-null   object
 7   CLREASND               0 non-null      float64
 8   CLCAT                  14595 non-null  object
 9   CLSEV                  99 non-null     object
 10  CLRFTDTC               14595 non-null  object
 11  CLTPTNUM               14246 non-null  float64
 12  CLDY                   14595 non-null  int64
 13  SEX                    14595 non-null  object
 14  trial_set_description  14595 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 1.8+ MB

In [112]:
cl_male_OPHTHALMOLOGY = cl[(cl["CLRESCAT"] == "OPHTHALMOLOGY") & (cl["SEX"] == "M")]
cl_male_OPHTHALMOLOGY.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1149 entries, 150 to 31369
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                1149 non-null   object
 1   USUBJID                1149 non-null   object
 2   CLLOC                  0 non-null      object
 3   STUDY_WEEK             761 non-null    float64
 4   CLORRES                1149 non-null   object
 5   CLRESCAT               1149 non-null   object
 6   CLSTAT                 761 non-null    object
 7   CLREASND               0 non-null      float64
 8   CLCAT                  1149 non-null   object
 9   CLSEV                  5 non-null      object
 10  CLRFTDTC               1149 non-null   object
 11  CLTPTNUM               1049 non-null   float64
 12  CLDY                   1149 non-null   int64
 13  SEX                    1149 non-null   object
 14  trial_set_description  1149 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 143.6+ KB

In [113]:
cl_female_OPHTHALMOLOGY = cl[(cl["CLRESCAT"] == "OPHTHALMOLOGY") & (cl["SEX"] == "F")]
cl_female_OPHTHALMOLOGY.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1128 entries, 38 to 31606
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                1128 non-null   object
 1   USUBJID                1128 non-null   object
 2   CLLOC                  0 non-null      object
 3   STUDY_WEEK             753 non-null    float64
 4   CLORRES                1128 non-null   object
 5   CLRESCAT               1128 non-null   object
 6   CLSTAT                 753 non-null    object
 7   CLREASND               0 non-null      float64
 8   CLCAT                  1128 non-null   object
 9   CLSEV                  4 non-null      object
 10  CLRFTDTC               1128 non-null   object
 11  CLTPTNUM               1032 non-null   float64
 12  CLDY                   1128 non-null   int64
 13  SEX                    1128 non-null   object
 14  trial_set_description  1128 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 141.0+ KB

In [114]:
cl_male_PHYSICAL_EXAM = cl[(cl["CLRESCAT"] == "PHYSICAL EXAM") & (cl["SEX"] == "M")]
cl_male_PHYSICAL_EXAM.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45 entries, 2632 to 25024
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                45 non-null     object
 1   USUBJID                45 non-null     object
 2   CLLOC                  0 non-null      object
 3   STUDY_WEEK             45 non-null     float64
 4   CLORRES                45 non-null     object
 5   CLRESCAT               45 non-null     object
 6   CLSTAT                 45 non-null     object
 7   CLREASND               0 non-null      float64
 8   CLCAT                  45 non-null     object
 9   CLSEV                  0 non-null      object
 10  CLRFTDTC               45 non-null     object
 11  CLTPTNUM               45 non-null     float64
 12  CLDY                   45 non-null     int64
 13  SEX                    45 non-null     object
 14  trial_set_description  45 non-null     object
dtypes: float64(3), int64(1), object(11)
memory usage: 5.6+ KB

In [115]:
cl_female_PHYSICAL_EXAM = cl[(cl["CLRESCAT"] == "PHYSICAL EXAM") & (cl["SEX"] == "F")]
cl_female_PHYSICAL_EXAM.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 1453 to 30186
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SPREFID                50 non-null     object
 1   USUBJID                50 non-null     object
 2   CLLOC                  10 non-null     object
 3   STUDY_WEEK             50 non-null     float64
 4   CLORRES                50 non-null     object
 5   CLRESCAT               50 non-null     object
 6   CLSTAT                 50 non-null     object
 7   CLREASND               0 non-null      float64
 8   CLCAT                  50 non-null     object
 9   CLSEV                  0 non-null      object
 10  CLRFTDTC               50 non-null     object
 11  CLTPTNUM               50 non-null     float64
 12  CLDY                   50 non-null     int64
 13  SEX                    50 non-null     object
 14  trial_set_description  50 non-null     object
dtypes: float64(3), int64(1), object(11)
memory usage: 6.2+ KB

In [116]:
cl_CLCAT_GROUP = cl["CLCAT"].unique()
cl_CLCAT_GROUP

array(['Detailed Clinical Observation', 'Open Field Observation',
       'Ophthalmology With Ophthalmoscope', 'Ophthalmology Pupil Reflex',
       'Ophthalmology Slit-Lamp Observation',
       'Daily Inspection of Animals', 'DETAILED CLINICAL OBSERVATION',
       'OPHTHALMOLOGY PUPIL REFLEX',
       'OPHTHALMOLOGY SLIT-LAMP OBSERVATION',
       'OPHTHALMOLOGY WITH OPHTHALMOSCOPE', 'OPEN-FIELD OBSERVATIONS',
       'DETAILED CLINICAL OBSERVATION INCL. OFO',
       'Open-Field Observation', 'Ophthalmology with Ophthalmoscope',
       'DAILY INSPECTION OF ANIMALS'], dtype=object)

In [137]:
cll = pd.DataFrame(cl["USUBJID"])
cl_USUBJID_GROUP = cll.groupby("USUBJID")
cl_USUBJID_GROUP.size()

USUBJID
HCD-01-0001    69
HCD-01-0002    69
HCD-01-0003    71
HCD-01-0004    69
HCD-01-0005    71
               ..
HCD-14-0067    74
HCD-14-0068    72
HCD-14-0069    72
HCD-14-0070    72
HCD-14-0071    72
Length: 322, dtype: int64

In [138]:
lb

,SPREFID,USUBJID,LBTEST,LBTESTCD,LBCAT,LBORRES,LBORRESU,LBMETHOD,LBSPEC,LBDY,trial_set_description,SEX
0,HCD-13,HCD-13-0042,Chloride,CL,CLINICAL CHEMISTRY,103.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
1,HCD-13,HCD-13-0044,Chloride,CL,CLINICAL CHEMISTRY,103.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
2,HCD-13,HCD-13-0049,Chloride,CL,CLINICAL CHEMISTRY,106.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
3,HCD-13,HCD-13-0047,Chloride,CL,CLINICAL CHEMISTRY,102.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
4,HCD-13,HCD-13-0048,Chloride,CL,CLINICAL CHEMISTRY,105.0,mmol/l,iBroker:CL-ISE,SERUM,34,CG,F
...,...,...,...,...,...,...,...,...,...,...,...,...
15452,HCD-02,HCD-02-0006,Volume,VOLUME,URINALYSIS,10.0,ml,iBroker:Volume,URINE,24,CG,M
15453,HCD-02,HCD-02-0008,Volume,VOLUME,URINALYSIS,9.7,ml,iBroker:Volume,URINE,24,CG,M
15454,HCD-02,HCD-02-0001,Volume,VOLUME,URINALYSIS,6.3,ml,iBroker:Volume,URINE,24,CG,M
15455,HCD-02,HCD-02-0009,Volume,VOLUME,URINALYSIS,3.8,ml,iBroker:Volume,URINE,24,CG,M
15456,HCD-02,HCD-02-0010,Volume,VOLUME,URINALYSIS,5.0,ml,iBroker:Volume,URINE,24,CG,M

In [161]:
lb_LBTEST_GROUP = lb["LBTEST"].unique()
print("The number of the LBTEST element", len(lb_LBTEST_GROUP))
lb_LBTEST_GROUP

The number of the LBTEST element 56

array(['Chloride', 'Protein', 'Protein/Creatinine', 'Leukocytes',
       'Sodium', 'Creatinine', 'Gamma Glutamyl Transferase',
       'Ery. Mean Corpuscular HGB Concentration', 'Bilirubin', 'Volume',
       'Erythrocytes', 'Albumin', 'Glutamate Dehydrogenase', 'Hematocrit',
       'Osmolality', 'Creatinine Excretion Rate', 'Monocytes', 'Urea',
       'Alkaline Phosphatase', 'Thrombocytes', 'Calcium', 'Eosinophils',
       'Lymphocytes', 'Ery. Mean Corpuscular Hemoglobin',
       'Alanine Aminotransferase', 'Cholesterol', 'Fibrinogen',
       'Aspartate Aminotransferase', 'Creatine Kinase', 'Hemoglobin',
       'Reticulocytes', 'Triglycerides', 'Prothrombin Time',
       'Lymphocytes Atypical, Reactive', 'Neutrophils', 'Basophils',
       'Glucose', 'Potassium', 'Ery. Mean Corpuscular Volume',
       'Lactate Dehydrogenase', 'Phosphate',
       'Activated Partial Thromboplastin Time',
       'Glutathione S-Transferase, Total', 'Lymphocytes Atypical',
       'Thyrotropin', '7-Ethoxycoumarin deethylase',
       '7-Ethoxyresorufin deethylase', 'Thyroxine',
       'Carnitine Acetyl Transferase', 'UDP-Glucuronyltransferase',
       'Triiodothyronine', 'ALD', 'Epoxide Hydrolase',
       'Protein per sampling period UVOL',
       'Protein per mmol Creatinine urine', 'Glucose whole blood'],
      dtype=object)

In [163]:
lb_LBTESTCD_GROUP = lb["LBTESTCD"].unique()
print("The number of the LBTESTCD element", len(lb_LBTESTCD_GROUP))
lb_LBTESTCD_GROUP

The number of the LBTESTCD element 56

array(['CL', 'PROT', 'PROTCRT', 'WBC', 'SODIUM', 'CREAT', 'GGT', 'MCHC',
       'BILI', 'VOLUME', 'RBC', 'ALB', 'GLDH', 'HCT', 'OSMLTY',
       'CREATEXR', 'MONO', 'UREA', 'ALP', 'THROMNUC', 'CA', 'EOS', 'LYM',
       'MCH', 'ALT', 'CHOL', 'FIBRINO', 'AST', 'CK', 'HGB', 'RETI',
       'TRIG', 'PT', 'ATYP', 'NEUT', 'BASO', 'GLUC', 'K', 'MCV', 'LDH',
       'PHOS', 'APTT', 'GST', 'LYMAT', 'TSH', 'ECOD', 'EROD', 'T4',
       'CARNITAT', 'UGT', 'T3', 'ALD', 'EH', 'UPROUVOC', 'UPROCRC',
       'GLUC_WB'], dtype=object)

In [148]:
# The columns LBTEST and LBTESTCD reverence the same values so one of them can be removed.
lb.iloc[123]

SPREFID                            HCD-13
USUBJID                       HCD-13-0045
LBTEST                         Creatinine
LBTESTCD                            CREAT
LBCAT                          URINALYSIS
LBORRES                              40.0
LBORRESU                             Âµmol
LBMETHOD                 iBroker:CRE*UVOL
LBSPEC                              URINE
LBDY                                   24
trial_set_description                  CG
SEX                                     F
Name: 123, dtype: object

In [165]:
lb_LBCAT_GROUP = lb["LBCAT"].unique()
lb_LBCAT_GROUP

array(['CLINICAL CHEMISTRY', 'URINALYSIS', 'HEMATOLOGY', 'COAGULATION',
       'ORGAN', 'BIOMARKER'], dtype=object)

In [167]:
ma

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
0,HCD-10,HCD-10-0082,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
1,HCD-10,HCD-10-0085,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
2,HCD-10,HCD-10-0081,OVIDUCT,NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
3,HCD-10,HCD-10-0081,"LARGE INTESTINE, CECUM",NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
4,HCD-10,HCD-10-0081,LIVER,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,HCD-09,HCD-09-0019,SPINAL CORD,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1902,HCD-09,HCD-09-0019,"GLAND, SALIVARY",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1903,HCD-09,HCD-09-0019,"GLAND, PARATHYROID",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1904,HCD-09,HCD-09-0074,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:48:40Z,Gross Pathological Examination,GROSPATH,1,F,CG
1905,HCD-09,HCD-09-0078,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:22:21Z,Gross Pathological Examination,GROSPATH,1,F,CG

In [173]:
ma_MASPEC_GROUP = ma["MASPEC"].unique()
ma_MASPEC_GROUP

array(['WHOLE ANIMAL', 'OVIDUCT', 'LARGE INTESTINE, CECUM', 'LIVER',
       'LYMPH NODE, ILIAC', 'NERVE, SCIATIC', 'BRAIN', 'NOSE', 'URETHRA',
       'BONE, FEMUR', 'SKIN/SUBCUTIS', 'SPLEEN', 'GLAND, PARATHYROID',
       'URETER', 'EYELID', 'KIDNEY', 'MUSCLE, SKELETAL',
       'SMALL INTESTINE', 'SPINAL CORD', 'LYMPH NODE, MANDIBULAR',
       'VAGINA', 'GLAND, THYROID', "PEYER'S PATCH", 'THYMUS', 'TONGUE',
       'LUNG', 'LYMPH NODE, MESENTERIC', 'BONE, STERNUM',
       'GLAND, SALIVARY, PAROTID', 'GLAND, LACRIMAL', 'GLAND, MAMMARY',
       'SMALL INTESTINE, ILEUM', 'URINARY BLADDER',
       'LARGE INTESTINE, COLON', 'STOMACH', 'BONE MARROW, FEMUR', 'EYE',
       'GLAND, SALIVARY', 'ARTERY, AORTA', 'ESOPHAGUS', 'GLAND, ADRENAL',
       'PANCREAS', 'TRACHEA', 'GLAND, ZYMBAL', 'HEAD', 'LARYNX',
       'SMALL INTESTINE, DUODENUM', 'LARGE INTESTINE', 'HEART', 'OVARY',
       'GLAND, PITUITARY', 'PHARYNX', 'TONSIL', 'UTERUS',
       'BONE MARROW, STERNUM', 'GLAND, HARDERIAN',
       'LARGE INTESTINE, RECTUM', 'SMALL INTESTINE, JEJUNUM',
       'GLAND, SEMINAL VESICLE', 'TESTIS', 'EPIDIDYMIS',
       'GLAND, PROSTATE', 'ALL TISSUES', 'BODY CAVITY', 'LYMPH NODE'],
      dtype=object)

In [213]:
ma_MASPEC_GROUP_ValueCounts = ma["MASPEC"].value_counts()
ma_MASPEC_GROUP_ValueCounts

WHOLE ANIMAL     223
ALL TISSUES       79
LIVER             29
EYE               29
SKIN/SUBCUTIS     29
                ...
OVARY             13
VAGINA            13
OVIDUCT           13
BODY CAVITY        5
LYMPH NODE         1
Name: MASPEC, Length: 65, dtype: int64

In [220]:
ma_MASPEC_MAORRES = ma[["MASPEC", "MAORRES"]].value_counts()
ma_MASPEC_MAORRES

MASPEC                    MAORRES
WHOLE ANIMAL              UNREMARKABLE                   221
ALL TISSUES               UNREMARKABLE                    79
GLAND, SALIVARY           UNREMARKABLE                    28
GLAND, SALIVARY, PAROTID  UNREMARKABLE                    28
LYMPH NODE, MESENTERIC    UNREMARKABLE                    28
                                                        ...
LIVER                     focus                            1
                          generalized: size increased      1
LYMPH NODE                UNREMARKABLE                     1
SKIN/SUBCUTIS             flank                            1
WHOLE ANIMAL              transponder not found            1
Length: 92, dtype: int64

In [228]:
ma_MASPEC_MAORRES_UNREMARKABLE = ma["MAORRES"].value_counts()
ma_MASPEC_MAORRES_UNREMARKABLE

UNREMARKABLE                              1870
discoloration                                9
discoloration red                            6
size decreased                               3
focus                                        1
died after blood sampling                    1
flank                                        1
head region                                  1
missing                                      1
Caudate lobe: discoloration                  1
Caudate lobe: consistency change             1
Right: pelvic dilatation                     1
swollen                                      1
right: destroyed during necropsy             1
left: organ missing, partly                  1
organ / tissue damaged during necropsy       1
transponder not found                        1
size increased                               1
right: pelvic dilatation                     1
containing watery fluid                      1
area                                         1
generalized: size increased                  1
Name: MAORRES, dtype: int64

In [174]:
ma_MAORRES_GROUP = ma["MAORRES"].unique()
ma_MAORRES_GROUP

array(['UNREMARKABLE', 'discoloration red', 'area', 'discoloration',
       'size decreased', 'containing watery fluid',
       'right: pelvic dilatation', 'size increased',
       'transponder not found', 'organ / tissue damaged during necropsy',
       'left: organ missing, partly', 'swollen',
       'right: destroyed during necropsy', 'focus',
       'Right: pelvic dilatation', 'Caudate lobe: consistency change',
       'Caudate lobe: discoloration', 'missing', 'head region', 'flank',
       'died after blood sampling', 'generalized: size increased'],
      dtype=object)

In [181]:
ma_MATEST_GROUP = ma["MATEST"].unique()
ma_MATEST_GROUP

array(['Gross Pathological Examination'], dtype=object)

In [179]:
ma_finding_is_unremarkable_or_incomplete = ma["finding_is_unremarkable_or_incomplete"].unique()
ma_finding_is_unremarkable_or_incomplete

array([1, 0], dtype=int64)

In [184]:
ma_finding_is_unremarkable_or_incomplete = ma["finding_is_unremarkable_or_incomplete"].value_counts()
ma_finding_is_unremarkable_or_incomplete

1    1870
0      36
Name: finding_is_unremarkable_or_incomplete, dtype: int64

In [232]:
ma_finding_is_unremarkable_or_incomplete_MALE1 = ma[(ma["finding_is_unremarkable_or_incomplete"] == 1) & (ma["SEX"] == "M")]
print("ma_finding_is_unremarkable_or_incomplete_MALE1", ma_finding_is_unremarkable_or_incomplete_MALE1.shape[0])
ma_finding_is_unremarkable_or_incomplete_MALE1

ma_finding_is_unremarkable_or_incomplete_MALE1 993

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
62,HCD-10,HCD-10-0010,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-07-12T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
64,HCD-10,HCD-10-0013,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
65,HCD-10,HCD-10-0003,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,30,2018-07-11T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
66,HCD-10,HCD-10-0012,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
67,HCD-10,HCD-10-0006,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,30,2018-07-11T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1898,HCD-09,HCD-09-0019,THYMUS,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1899,HCD-09,HCD-09-0019,TONGUE,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1901,HCD-09,HCD-09-0019,SPINAL CORD,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1902,HCD-09,HCD-09-0019,"GLAND, SALIVARY",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1903,HCD-09,HCD-09-0019,"GLAND, PARATHYROID",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG

In [207]:
ma_finding_is_unremarkable_or_incomplete_FEMALE1 = ma[(ma["finding_is_unremarkable_or_incomplete"] == 1) & (ma["SEX"] == "F")]
print("ma_finding_is_unremarkable_or_incomplete_FEMALE1", ma_finding_is_unremarkable_or_incomplete_FEMALE1.shape[0])
ma_finding_is_unremarkable_or_incomplete_FEMALE1

ma_finding_is_unremarkable_or_incomplete_FEMALE1 877

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
0,HCD-10,HCD-10-0082,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
1,HCD-10,HCD-10-0085,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
2,HCD-10,HCD-10-0081,OVIDUCT,NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
3,HCD-10,HCD-10-0081,"LARGE INTESTINE, CECUM",NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
4,HCD-10,HCD-10-0081,LIVER,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1839,HCD-09,HCD-09-0083,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T14:22:50Z,Gross Pathological Examination,GROSPATH,1,F,CG
1840,HCD-09,HCD-09-0088,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,F,CG
1841,HCD-09,HCD-09-0081,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T14:22:50Z,Gross Pathological Examination,GROSPATH,1,F,CG
1904,HCD-09,HCD-09-0074,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:48:40Z,Gross Pathological Examination,GROSPATH,1,F,CG
1905,HCD-09,HCD-09-0078,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:22:21Z,Gross Pathological Examination,GROSPATH,1,F,CG

In [208]:
ma_finding_is_unremarkable_or_incomplete_MALE0 = ma[(ma["finding_is_unremarkable_or_incomplete"] == 0) & (ma["SEX"] == "M")]
print("ma_finding_is_unremarkable_or_incomplete_MALE0", ma_finding_is_unremarkable_or_incomplete_MALE0.shape[0])
ma_finding_is_unremarkable_or_incomplete_MALE0

ma_finding_is_unremarkable_or_incomplete_MALE0 19

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
111,HCD-10,HCD-10-0008,LIVER,NaN,NaN,area,NaN,NaN,NaN,31,2018-07-12T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
172,HCD-10,HCD-10-0002,TESTIS,NaN,NaN,discoloration,BILATERAL,NaN,NaN,30,2018-07-11T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
215,HCD-10,HCD-10-0007,"GLAND, SEMINAL VESICLE",NaN,NaN,size decreased,BILATERAL,NaN,NaN,30,2018-07-11T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
370,HCD-08,HCD-08-0007,KIDNEY,NaN,NaN,right: pelvic dilatation,BILATERAL,NaN,NaN,30,2018-04-18T09:37:06Z,Gross Pathological Examination,GROSPATH,0,M,CG
477,HCD-05,HCD-05-0019,KIDNEY,NaN,NaN,discoloration,BILATERAL,NaN,NaN,58,2017-05-18T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
661,HCD-05,HCD-05-0015,WHOLE ANIMAL,NaN,NaN,transponder not found,NaN,NaN,NaN,58,2017-05-18T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
828,HCD-03,HCD-03-0001,EYE,NaN,NaN,right: destroyed during necropsy,BILATERAL,NaN,NaN,30,2017-03-22T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
910,HCD-03,HCD-03-0005,KIDNEY,NaN,NaN,discoloration,BILATERAL,NaN,NaN,30,2017-03-22T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1070,HCD-03,HCD-03-0018,THYMUS,NaN,NaN,discoloration,NaN,NaN,NaN,44,2017-04-05T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1126,HCD-03,HCD-03-0018,"LYMPH NODE, MANDIBULAR",NaN,NaN,discoloration red,BILATERAL,NaN,NaN,44,2017-04-05T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1147,HCD-03,HCD-03-0004,"LYMPH NODE, MANDIBULAR",NaN,NaN,discoloration red,BILATERAL,NaN,NaN,30,2017-03-22T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1198,HCD-03,HCD-03-0015,TESTIS,NaN,NaN,size decreased,BILATERAL,NaN,NaN,44,2017-04-05T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1242,HCD-03,HCD-03-0015,EPIDIDYMIS,NaN,NaN,size decreased,BILATERAL,NaN,NaN,44,2017-04-05T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1355,HCD-02,HCD-02-0009,KIDNEY,NaN,NaN,discoloration,BILATERAL,NaN,NaN,31,2017-03-02T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1509,HCD-13,HCD-13-0008,"GLAND, HARDERIAN",NaN,NaN,discoloration,BILATERAL,NaN,NaN,31,2019-12-06T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1542,HCD-12,HCD-12-0015,KIDNEY,NaN,NaN,Right: pelvic dilatation,BILATERAL,NaN,NaN,43,2019-05-28T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1547,HCD-12,HCD-12-0015,LIVER,NaN,NaN,Caudate lobe: consistency change,NaN,NaN,NaN,43,2019-05-28T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1548,HCD-12,HCD-12-0015,LIVER,NaN,NaN,Caudate lobe: discoloration,NaN,NaN,NaN,43,2019-05-28T00:00:00Z,Gross Pathological Examination,GROSPATH,0,M,CG
1900,HCD-09,HCD-09-0019,LIVER,NaN,NaN,generalized: size increased,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,0,M,CG

In [209]:
ma_finding_is_unremarkable_or_incomplete_FEMALE0 = ma[(ma["finding_is_unremarkable_or_incomplete"] == 0) & (ma["SEX"] == "F")]
print("ma_finding_is_unremarkable_or_incomplete_FEMALE0", ma_finding_is_unremarkable_or_incomplete_FEMALE0.shape[0])
ma_finding_is_unremarkable_or_incomplete_FEMALE0

ma_finding_is_unremarkable_or_incomplete_FEMALE0 17

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
21,HCD-10,HCD-10-0081,"LYMPH NODE, MANDIBULAR",NaN,NaN,discoloration red,BILATERAL,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
285,HCD-06,HCD-06-0065,UTERUS,NaN,NaN,containing watery fluid,NaN,NaN,NaN,30,2017-05-09T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
511,HCD-05,HCD-05-0074,"LYMPH NODE, MANDIBULAR",NaN,NaN,discoloration red,BILATERAL,NaN,NaN,31,2017-04-21T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
602,HCD-05,HCD-05-0075,"GLAND, ADRENAL",NaN,NaN,size increased,BILATERAL,NaN,NaN,31,2017-04-21T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
713,HCD-03,HCD-03-0075,URINARY BLADDER,NaN,NaN,organ / tissue damaged during necropsy,NaN,NaN,NaN,32,2017-03-24T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
769,HCD-03,HCD-03-0081,EYE,NaN,NaN,"left: organ missing, partly",BILATERAL,NaN,NaN,32,2017-03-24T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
771,HCD-03,HCD-03-0081,KIDNEY,NaN,NaN,discoloration,BILATERAL,NaN,NaN,32,2017-03-24T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
786,HCD-03,HCD-03-0081,EYE,NaN,NaN,discoloration,BILATERAL,NaN,NaN,32,2017-03-24T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
815,HCD-03,HCD-03-0081,SPLEEN,NaN,NaN,swollen,NaN,NaN,NaN,32,2017-03-24T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
964,HCD-03,HCD-03-0089,"LYMPH NODE, MANDIBULAR",NaN,NaN,discoloration red,BILATERAL,NaN,NaN,44,2017-04-05T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
1052,HCD-03,HCD-03-0092,"LYMPH NODE, MANDIBULAR",NaN,NaN,discoloration red,BILATERAL,NaN,NaN,44,2017-04-05T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
1267,HCD-02,HCD-02-0095,THYMUS,NaN,NaN,discoloration,NaN,NaN,NaN,32,2017-03-03T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
1434,HCD-02,HCD-02-0098,LIVER,NaN,NaN,focus,NaN,NaN,NaN,32,2017-03-03T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
1641,HCD-04,HCD-04-0082,EYE,NaN,NaN,missing,BILATERAL,NaN,NaN,30,2017-04-12T00:00:00Z,Gross Pathological Examination,GROSPATH,0,F,CG
1721,HCD-09,HCD-09-0082,SKIN/SUBCUTIS,NaN,NaN,head region,NaN,NaN,NaN,31,2018-05-30T14:22:50Z,Gross Pathological Examination,GROSPATH,0,F,CG
1722,HCD-09,HCD-09-0082,SKIN/SUBCUTIS,NaN,NaN,flank,NaN,NaN,NaN,31,2018-05-30T14:22:50Z,Gross Pathological Examination,GROSPATH,0,F,CG
1782,HCD-09,HCD-09-0076,WHOLE ANIMAL,NaN,NaN,died after blood sampling,NaN,NaN,NaN,30,2018-05-29T07:57:27Z,Gross Pathological Examination,GROSPATH,0,F,CG

The Cloumns `MAORRES` and `finding_is_unremarkable_or_incomplete` reverce to the same values since there is unremarkable

In [230]:
ma_MAORRES_MALE = ma[(ma["MAORRES"] == "UNREMARKABLE") & (ma["SEX"] == "M")]
print("ma_MAORRES_MALE", ma_MAORRES_MALE.shape[0])
ma_MAORRES_MALE

ma_MAORRES_MALE 993

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
62,HCD-10,HCD-10-0010,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-07-12T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
64,HCD-10,HCD-10-0013,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
65,HCD-10,HCD-10-0003,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,30,2018-07-11T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
66,HCD-10,HCD-10-0012,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
67,HCD-10,HCD-10-0006,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,30,2018-07-11T00:00:00Z,Gross Pathological Examination,GROSPATH,1,M,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1898,HCD-09,HCD-09-0019,THYMUS,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1899,HCD-09,HCD-09-0019,TONGUE,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1901,HCD-09,HCD-09-0019,SPINAL CORD,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1902,HCD-09,HCD-09-0019,"GLAND, SALIVARY",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG
1903,HCD-09,HCD-09-0019,"GLAND, PARATHYROID",NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,M,CG

In [231]:
ma_MAORRES_FEMALE = ma[(ma["MAORRES"] == "UNREMARKABLE") & (ma["SEX"] == "F")]
print("ma_MAORRES_FEMALE", ma_MAORRES_FEMALE.shape[0])
ma_MAORRES_FEMALE

ma_MAORRES_FEMALE 877

,SPREFID,USUBJID,MASPEC,MASEVN,MASEV,MAORRES,MALAT,MASTAT,MAREASND,MADY,MADTC,MATEST,MATESTCD,finding_is_unremarkable_or_incomplete,SEX,trial_set_description
0,HCD-10,HCD-10-0082,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
1,HCD-10,HCD-10-0085,WHOLE ANIMAL,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-08-09T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
2,HCD-10,HCD-10-0081,OVIDUCT,NaN,NaN,UNREMARKABLE,BILATERAL,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
3,HCD-10,HCD-10-0081,"LARGE INTESTINE, CECUM",NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
4,HCD-10,HCD-10-0081,LIVER,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,32,2018-07-13T00:00:00Z,Gross Pathological Examination,GROSPATH,1,F,CG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1839,HCD-09,HCD-09-0083,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T14:22:50Z,Gross Pathological Examination,GROSPATH,1,F,CG
1840,HCD-09,HCD-09-0088,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,57,2018-06-25T12:38:54Z,Gross Pathological Examination,GROSPATH,1,F,CG
1841,HCD-09,HCD-09-0081,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T14:22:50Z,Gross Pathological Examination,GROSPATH,1,F,CG
1904,HCD-09,HCD-09-0074,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:48:40Z,Gross Pathological Examination,GROSPATH,1,F,CG
1905,HCD-09,HCD-09-0078,ALL TISSUES,NaN,NaN,UNREMARKABLE,NaN,NaN,NaN,31,2018-05-30T08:22:21Z,Gross Pathological Examination,GROSPATH,1,F,CG

In [283]:
mi

,SPREFID,USUBJID,SEX,MISPEC,MISEVTXT,MISEV,MIORRES,MIRESCAT,MIDY,trial_set_description
0,HCD-05,HCD-05-0015,M,"SMALL INTESTINE, ILEUM",NaN,NaN,UNREMARKABLE,NaN,58,CG
1,HCD-05,HCD-05-0015,M,"LARGE INTESTINE, RECTUM",NaN,NaN,UNREMARKABLE,NaN,58,CG
2,HCD-05,HCD-05-0015,M,TRACHEA,NaN,NaN,UNREMARKABLE,NaN,58,CG
3,HCD-05,HCD-05-0015,M,ESOPHAGUS,NaN,NaN,UNREMARKABLE,NaN,58,CG
4,HCD-05,HCD-05-0015,M,PEYER'S PATCH,NaN,NaN,UNREMARKABLE,NaN,58,CG
...,...,...,...,...,...,...,...,...,...,...
14126,HCD-07,HCD-07-0001,M,SKIN,NaN,NaN,UNREMARKABLE,NaN,29,CG
14127,HCD-07,HCD-07-0001,M,EYE,NaN,NaN,UNREMARKABLE,NaN,29,CG
14128,HCD-07,HCD-07-0001,M,"LARGE INTESTINE, RECTUM",NaN,NaN,UNREMARKABLE,NaN,29,CG
14129,HCD-07,HCD-07-0001,M,SPINAL CORD,NaN,NaN,UNREMARKABLE,NaN,29,CG
14130,HCD-07,HCD-07-0001,M,TESTIS,NaN,NaN,UNREMARKABLE,NaN,29,CG

In [238]:
mi_SEX = mi["SEX"].value_counts()
mi_SEX

M    7251
F    6880
Name: SEX, dtype: int64

In [253]:
mi_MISPEC = mi["MISPEC"].unique()
mi_MISPEC

array(['SMALL INTESTINE, ILEUM', 'LARGE INTESTINE, RECTUM', 'TRACHEA',
       'ESOPHAGUS', "PEYER'S PATCH", 'GLAND, THYROID', 'SPLEEN',
       'SMALL INTESTINE, JEJUNUM', 'THYMUS', 'BONE MARROW, FEMUR',
       'LARGE INTESTINE, CECUM', 'GLAND, PARATHYROID', 'GLAND, PITUITARY',
       'STOMACH', 'BONE, FEMUR', 'PANCREAS', 'BONE MARROW, STERNUM',
       'LARGE INTESTINE, COLON', 'LIVER', 'WHOLE ANIMAL',
       'GLAND, ADRENAL', 'SMALL INTESTINE, DUODENUM', 'BONE, STERNUM',
       'EYE', 'KIDNEY', 'NERVE, OPTIC', 'GLAND, SALIVARY, PAROTID',
       'LYMPH NODE, MESENTERIC', 'LYMPH NODE, ILIAC', 'SPINAL CORD',
       'ARTERY, AORTA', 'GLAND, HARDERIAN', 'SKIN', 'GLAND, MAMMARY',
       'VAGINA', 'LUNG', 'URINARY BLADDER', 'UTERUS', 'TONGUE',
       'NERVE, SCIATIC', 'HEART', 'BRAIN', 'URETER', 'GLAND, LACRIMAL',
       'LARYNX', 'LYMPH NODE, MANDIBULAR', 'OVIDUCT',
       'GLAND, SALIVARY, SUBLINGUAL', 'MUSCLE, SKELETAL', 'OVARY',
       'SKIN/SUBCUTIS', 'GLAND, SALIVARY, SUBMANDIBULAR',
       'GLAND, PROSTATE', 'GLAND, SEMINAL VESICLE', 'TESTIS',
       'GLAND, COAGULATING', 'EPIDIDYMIS', 'FORESTOMACH',
       'STOMACH, GLANDULAR', 'CERVIX', 'TONSIL', 'HEAD', 'PHARYNX',
       'SMALL INTESTINE', 'GLAND, SALIVARY', 'GLAND, ZYMBAL', 'NOSE',
       'EYELID', 'URETHRA', 'LARGE INTESTINE', 'BRAIN, MEDULLA OBLONGATA',
       'BRAIN, CEREBRUM', 'BRAIN, CEREBELLUM', 'BODY CAVITY'],
      dtype=object)

In [258]:
om.head(50)

,SPREFID,USUBJID,OMEXCLFL,OMSTAT,OMREASND,OMTESTCD,OMTEST,OMSPEC,OMSTRES,OMSTRESU,OMDY,SEX,trial_set_description
0,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,THYMUS,0.18757,%,29,M,CG
1,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,THYMUS,0.52200,g,29,M,CG
2,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,SPLEEN,0.19799,%,29,M,CG
3,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,SPLEEN,0.55100,g,29,M,CG
4,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, ADRENAL",0.01365,%,29,M,CG
5,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, ADRENAL",0.03800,g,29,M,CG
6,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, SEMINAL VESICLE",0.28387,%,29,M,CG
7,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, SEMINAL VESICLE",0.79000,g,29,M,CG
8,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, PROSTATE",0.19081,%,29,M,CG
9,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, PROSTATE",0.53100,g,29,M,CG
10,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,EPIDIDYMIS,0.36365,%,29,M,CG
11,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,EPIDIDYMIS,1.01200,g,29,M,CG
12,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,TESTIS,1.13550,%,29,M,CG
13,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,TESTIS,3.16000,g,29,M,CG
14,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,KIDNEY,0.64932,%,29,M,CG
15,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,KIDNEY,1.80700,g,29,M,CG
16,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,LIVER,3.77340,%,29,M,CG
17,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,LIVER,10.50100,g,29,M,CG
18,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,HEART,0.30795,%,29,M,CG
19,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,HEART,0.85700,g,29,M,CG
20,HCD-05,HCD-05-0006,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,BRAIN,0.73268,%,29,M,CG
21,HCD-05,HCD-05-0006,NaN,NaN,NaN,WEIGHT,Weight,BRAIN,2.03900,g,29,M,CG
22,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,THYMUS,0.17169,%,58,M,CG
23,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,THYMUS,0.63100,g,58,M,CG
24,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,SPLEEN,0.18339,%,58,M,CG
25,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,SPLEEN,0.67400,g,58,M,CG
26,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, ADRENAL",0.02177,%,58,M,CG
27,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, ADRENAL",0.08000,g,58,M,CG
28,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, SEMINAL VESICLE",0.32134,%,58,M,CG
29,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, SEMINAL VESICLE",1.18100,g,58,M,CG
30,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, PROSTATE",0.37957,%,58,M,CG
31,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, PROSTATE",1.39500,g,58,M,CG
32,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,EPIDIDYMIS,0.44161,%,58,M,CG
33,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,EPIDIDYMIS,1.62300,g,58,M,CG
34,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,TESTIS,1.00670,%,58,M,CG
35,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,TESTIS,3.70000,g,58,M,CG
36,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,KIDNEY,0.71479,%,58,M,CG
37,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,KIDNEY,2.62700,g,58,M,CG
38,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,LIVER,3.65610,%,58,M,CG
39,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,LIVER,13.43700,g,58,M,CG
40,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,HEART,0.27645,%,58,M,CG
41,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,HEART,1.01600,g,58,M,CG
42,HCD-05,HCD-05-0016,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,BRAIN,0.50718,%,58,M,CG
43,HCD-05,HCD-05-0016,NaN,NaN,NaN,WEIGHT,Weight,BRAIN,1.86400,g,58,M,CG
44,HCD-05,HCD-05-0082,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,THYMUS,0.17237,%,30,F,CG
45,HCD-05,HCD-05-0082,NaN,NaN,NaN,WEIGHT,Weight,THYMUS,0.34000,g,30,F,CG
46,HCD-05,HCD-05-0082,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,SPLEEN,0.18606,%,30,F,CG
47,HCD-05,HCD-05-0082,NaN,NaN,NaN,WEIGHT,Weight,SPLEEN,0.36700,g,30,F,CG
48,HCD-05,HCD-05-0082,NaN,NaN,NaN,OWBW,Organ to Body Weight Ratio,"GLAND, ADRENAL",0.03701,%,30,F,CG
49,HCD-05,HCD-05-0082,NaN,NaN,NaN,WEIGHT,Weight,"GLAND, ADRENAL",0.07300,g,30,F,CG

In [255]:
om_SEX = om["SEX"].value_counts()
om_SEX

M    3370
F    2524
Name: SEX, dtype: int64

In [277]:
om_SEX_OMTEST_OWBW_MALE = om[["SEX","OMTESTCD","OMSTRES"]]
om_SEX_OMTEST_OWBW_MALE = om_SEX_OMTEST_OWBW_MALE[(om_SEX_OMTEST_OWBW_MALE["SEX"] == "M") & (om_SEX_OMTEST_OWBW_MALE["OMTESTCD"] == "OWBW")]
print("Mean of om_SEX_OMTEST_OWBW_MALE", om_SEX_OMTEST_OWBW_MALE.mean())
om_SEX_OMTEST_OWBW_MALE

Mean of om_SEX_OMTEST_OWBW_MALE OMSTRES    0.720085
dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_12600\1518327052.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("Mean of om_SEX_OMTEST_OWBW_MALE", om_SEX_OMTEST_OWBW_MALE.mean())

     SEX OMTESTCD  OMSTRES
0      M     OWBW  0.18757
2      M     OWBW  0.19799
4      M     OWBW  0.01365
6      M     OWBW  0.28387
8      M     OWBW  0.19081
...   ..      ...      ...
5885   M     OWBW  3.56060
5887   M     OWBW  0.69183
5889   M     OWBW  0.36779
5891   M     OWBW  0.21840
5893   M     OWBW  0.01912

[1685 rows x 3 columns]

In [288]:
om_SEX_OMTEST_OWBW_FEMALE = om[["SEX","OMTESTCD","OMSTRES"]]
om_SEX_OMTEST_OWBW_FEMALE = om_SEX_OMTEST_OWBW_FEMALE[(om_SEX_OMTEST_OWBW_FEMALE["SEX"] == "F") & (om_SEX_OMTEST_OWBW_FEMALE["OMTESTCD"] == "OWBW")]
print("Mean of om_SEX_OMTEST_OWBW_FEMALE", om_SEX_OMTEST_OWBW_FEMALE.mean())
om_SEX_OMTEST_OWBW_FEMALE

Mean of om_SEX_OMTEST_OWBW_FEMALE OMSTRES    0.796899
dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_12600\2241075398.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("Mean of om_SEX_OMTEST_OWBW_FEMALE", om_SEX_OMTEST_OWBW_FEMALE.mean())

     SEX OMTESTCD  OMSTRES
44     F     OWBW  0.17237
46     F     OWBW  0.18606
48     F     OWBW  0.03701
50     F     OWBW  0.22155
52     F     OWBW  0.75285
...   ..      ...      ...
5863   F     OWBW  0.17657
5865   F     OWBW  0.04051
5867   F     OWBW  0.19838
5869   F     OWBW  0.08309
5871   F     OWBW  0.98931

[1262 rows x 3 columns]

In [289]:
om_SEX_OMTEST_WEIGHT_MALE = om[["SEX","OMTESTCD","OMSTRES"]]
om_SEX_OMTEST_WEIGHT_MALE = om_SEX_OMTEST_WEIGHT_MALE[(om_SEX_OMTEST_WEIGHT_MALE["SEX"] == "M") & (om_SEX_OMTEST_WEIGHT_MALE["OMTESTCD"] == "WEIGHT")]
print("Mean of om_SEX_OMTEST_WEIGHT_MALE", om_SEX_OMTEST_WEIGHT_MALE.mean())
om_SEX_OMTEST_WEIGHT_MALE

Mean of om_SEX_OMTEST_WEIGHT_MALE OMSTRES    2.228618
dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_12600\3394732857.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("Mean of om_SEX_OMTEST_WEIGHT_MALE", om_SEX_OMTEST_WEIGHT_MALE.mean())

     SEX OMTESTCD  OMSTRES
1      M   WEIGHT    0.522
3      M   WEIGHT    0.551
5      M   WEIGHT    0.038
7      M   WEIGHT    0.790
9      M   WEIGHT    0.531
...   ..      ...      ...
5884   M   WEIGHT   10.988
5886   M   WEIGHT    2.135
5888   M   WEIGHT    3.914
5890   M   WEIGHT    0.674
5892   M   WEIGHT    0.856

[1685 rows x 3 columns]

In [291]:
om_SEX_OMTEST_WEIGHT_FEMALE = om[["SEX","OMTESTCD","OMSTRES"]]
om_SEX_OMTEST_WEIGHT_FEMALE = om_SEX_OMTEST_WEIGHT_FEMALE[(om_SEX_OMTEST_WEIGHT_FEMALE["SEX"] == "F") & (om_SEX_OMTEST_WEIGHT_FEMALE["OMTESTCD"] == "WEIGHT")]
print("Mean of om_SEX_OMTEST_WEIGHT_FEMALE", om_SEX_OMTEST_WEIGHT_FEMALE.mean())
om_SEX_OMTEST_WEIGHT_FEMALE

Mean of om_SEX_OMTEST_WEIGHT_FEMALE OMSTRES    1.66989
dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_12600\1562044554.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("Mean of om_SEX_OMTEST_WEIGHT_FEMALE", om_SEX_OMTEST_WEIGHT_FEMALE.mean())

     SEX OMTESTCD  OMSTRES
45     F   WEIGHT    0.340
47     F   WEIGHT    0.367
49     F   WEIGHT    0.073
51     F   WEIGHT    0.437
53     F   WEIGHT    1.485
...   ..      ...      ...
5862   F   WEIGHT    0.379
5864   F   WEIGHT    0.340
5866   F   WEIGHT    0.078
5868   F   WEIGHT    0.382
5870   F   WEIGHT    0.160

[1262 rows x 3 columns]

In [292]:
ts

,SPREFID,SPECIES,STRAIN,AGE,AGEU,DOSDUR,ROUTE,TRTV,TSTFLOC,START_YEAR,STDSTDTC,STITLE
0,HCD-09,RAT,WISTAR HAN,7-8,WEEKS,4 week,INTRAGASTRIC,Ethanol/KolliphorHS15/WaterfI,"42096 Wuppertal, Germany",2018,2018-04-17,Repeated Dose Systemic Toxicity Study in Wista...
1,HCD-05,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-03-14,Repeated Dose Systemic Toxicity Study in Wista...
2,HCD-04,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-03-07,Repeated Dose Systemic Toxicity Study in Wista...
3,HCD-08,RAT,WISTAR HAN,NaN,WEEKS,4 week,ORAL,Kolliphor HS 15/ethanol/water (40/10/50; v/v/v),42096 Wuppertal,2018,2018-03-15,Repeated Dose Systemic Toxicity Study in Wista...
4,HCD-01,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,PEG 400 / Ethanol,"Wuppertal, Germany",2017,2017-01-10,4-Week Repeated Dose Systemic Toxicity Study i...
5,HCD-10,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2018,2018-06-05,Repeated Dose Systemic Toxicity Study in Wista...
6,HCD-12,RAT,WISTAR,NaN,WEEKS,4 week,ORAL,PEG 400/Ethanol (90/10; v/v),"GLP-Prufeinrichtung Early Development Bayer, 4...",2019,2019-04-08,4- Week Repeat Dose Systemic Toxicity Study in...
7,HCD-11,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2019,2019-03-26,Repeated Dose Systemic Toxicity Study in Male ...
8,HCD-06,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-03-21,4-Week Repeat Dose Systemic Toxicity Study in ...
9,HCD-07,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-06-02,4-Week Repeat Dose Systemic Toxicity Study in ...
10,HCD-14,RAT,WISTAR,NaN,NaN,4 week,ORAL GAVAGE,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2020,2020-11-10,4-Week Repeat Dose Systemic Toxicity Study in ...
11,HCD-13,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,PEG400/Cremophor/Imwitor+SDS,"Wuppertal, Germany",2019,2019-10-29,Repeated Dose Systemic Toxicity Study in Rats ...
12,HCD-03,RAT,WISTAR HAN,NaN,NaN,4 week,ORAL,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-02-14,Repeated Dose Systemic Toxicity Study in Wista...
13,HCD-02,RAT,WISTAR HAN,NaN,NaN,4 week,INTRAGASTRIC,Ethanol/KolliphorHS15/WaterfI,"Wuppertal, Germany",2017,2017-01-24,Repeated Dose Systemic Toxicity Study in Wista...

In [293]:
# We can remove this column
ts["DOSDUR"].unique()

array(['4 week'], dtype=object)

In [294]:
ts["ROUTE"].unique()

array(['INTRAGASTRIC', 'ORAL', 'ORAL GAVAGE'], dtype=object)

In [296]:
ts["AGE"].value_counts()

7-8    1
Name: AGE, dtype: int64

In [297]:
ts["STRAIN"].value_counts()

WISTAR HAN    12
WISTAR         2
Name: STRAIN, dtype: int64

In [298]:
ts["TRTV"].value_counts()

Ethanol/KolliphorHS15/WaterfI                      10
Kolliphor HS 15/ethanol/water (40/10/50; v/v/v)     1
PEG 400 / Ethanol                                   1
PEG 400/Ethanol (90/10; v/v)                        1
PEG400/Cremophor/Imwitor+SDS                        1
Name: TRTV, dtype: int64